vich_uploader:
  db_driver: orm

  metadata:
    type: attribute

  mappings:
    deals:
      uri_prefix: /images/upload/deals
      upload_destination: "%kernel.project_dir%/public/images/upload/deals"
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

      inject_on_load: false
      delete_on_update: true
      delete_on_remove: true

    categories:
      uri_prefix: /images/upload/categories
      upload_destination: "%kernel.project_dir%/public/images/upload/categories"
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

      inject_on_load: false
      delete_on_update: true
      delete_on_remove: true

    users:
      uri_prefix: /images/upload/users
      upload_destination: "%kernel.project_dir%/public/images/upload/users"
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

      inject_on_load: false
      delete_on_update: true
      delete_on_remove: true
